{
 "title": "Dremio Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "label_values(metrics_reflections_active_Value, job)"
   },
   {
    "name": "timeRange",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,2d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(process_start_time_seconds{job=~\"$Cluster\"}) by (job) * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - min(process_start_time_seconds{job=~\"$Cluster\"}) by (job)"
    }
   ]
  },
  {
   "title": "Executor Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dremio_sql_executors_Value{job=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Queries in waiting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(metrics_jobs_command_pool_queue_size_Value{job=~\"$Cluster\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "RPC Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(metrics_rpc_failure_15m_Value{job=~\"$Cluster\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(metrics_jobs_active_15m_Value{job=~\"$Cluster\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Active Jobs - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_jobs_active_Value{job=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(metrics_jobs_failed_15m_Value{job=~\"$Cluster\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Good Data Source Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dremio_api_source_status_Value{job=~\"$Cluster\"} == 200)"
    }
   ]
  },
  {
   "title": "Bad Data Source Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dremio_api_source_status_Value{job=~\"$Cluster\"} != 200)",
     "legendFormat": "count_bad"
    }
   ]
  },
  {
   "title": "VDS Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "dremio_sql_vds_count_Value{job=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Usable Reflection Count - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_reflections_active_Value{job=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Reflections Refreshing - Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "metrics_reflections_refreshing_Value{job=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Failed Reflection Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(metrics_reflections_failed_Value{job=~\"$Cluster\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(dremio_sql_executors_Value{job=\"$Cluster\"}) by (executor)"
    }
   ]
  },
  {
   "title": "Queries waiting by Queue",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Number of Queries" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(metrics_jobs_queue_LowCostUserQueries_waiting_Value{job=\"$Cluster\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"metrics_jobs_queue_(.*)_waiting_Value\")",
     "legendFormat": "{{ _1_queue }}"
    }
   ]
  },
  {
   "title": "Threads in Waiting",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(sum(dremio_sql_threads_waiting_Value{job=\"$Cluster\"}) by (cluster, executor), \"state\", \"$1\", \"__name__\", \"metrics_dremio_executor_threads_(.*)_Value\")"
    }
   ]
  },
  {
   "title": "Heap memory Usage - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(metrics_memory_heap_used_Value{job=\"$Cluster\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{ short_hostname }}: Used"
    },
    {
     "expr": "label_replace(metrics_memory_heap_max_Value{job=\"$Cluster\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{ short_hostname }}: Max"
    }
   ]
  },
  {
   "title": "Disk Usage - Coordinators",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "label_replace(max(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (instance, mountpoint), \"_0_short_hostname\", \"$1\", \"instance\", \"(.*):.*\")"
    },
    {
     "expr": "max(node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}) by (instance, mountpoint)"
    },
    {
     "expr": "1-max((node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"})) by (instance, mountpoint)"
    }
   ]
  },
  {
   "title": "Garbage Collection Time - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(jvm_gc_collection_seconds_sum{job=\"$Cluster\"}[5m]), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\") / label_replace(rate(jvm_gc_collection_seconds_count{job=\"$Cluster\"}[5m]), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}:{{gc}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Coordinators",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(node_memory_MemTotal_bytes) by (instance), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}:Total"
    },
    {
     "expr": "label_replace(avg(node_memory_MemAvailable_bytes) by (instance), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}: Available"
    }
   ]
  },
  {
   "title": "Garbage Collection Counts - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(jvm_gc_collection_seconds_count{job=\"$Cluster\"}[5m]), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}:{{ gc }} "
    }
   ]
  },
  {
   "title": "CPU Usage - Coordinators",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) by (instance), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Direct  memory Usage - Executors",
   "type": "graph",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(dremio_sql_executor_direct_current_Value{job=\"$Cluster\"}) by (cluster, instance)",
     "legendFormat": "{{instance}}:{{cluster}} - Current"
    },
    {
     "expr": "sum(dremio_sql_executor_direct_max_Value{job=\"$Cluster\"}) by (cluster, instance)",
     "legendFormat": "{{instance}}:{{cluster}} - Max"
    }
   ]
  },
  {
   "title": "Network Usage - Coordinators",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[15m])) by (instance, device), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}-{{device}}: Receive"
    },
    {
     "expr": "label_replace(avg(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[15m])) by (instance, device), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}-{{device}}: Transmit"
    }
   ]
  },
  {
   "title": "Disk IO - Coordinators",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(rate(node_disk_read_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])) by (instance, device), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}_{{device}}_Read bytes"
    },
    {
     "expr": "label_replace(avg(rate(node_disk_written_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])) by (instance, device), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}_{{device}}_Written bytes"
    }
   ]
  }
 ]
}