{
 "title": "Dremio Summary Dashboard",
 "tags": [ "Dremio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "label_values(metrics_reflections_active_Value, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Coordinator Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(dremio_api_coordinator_up{job=~\"$Cluster\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"), \"_1_instance\", \"$1\", \"instance\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Source Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dremio_api_source_status_Value{job=~\"$Cluster\"} + 0"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(dremio_api_total_executors_Value{job=~\"$Cluster\"}) by(cluster, job), \"_0_cluster\", \"$1\", \"job\", \"(.*)\"), \"_1_subcluster\", \"$1\", \"cluster\", \"(.*)\")"
    },
    {
     "expr": "sum(dremio_api_current_executors_Value{job=~\"$Cluster\"}) by (cluster, job)"
    },
    {
     "expr": "dremio_api_cluster_allocated_memory_Value{job=~\"$Cluster\"} + 0"
    },
    {
     "expr": "dremio_api_cluster_used_memory_Value{job=~\"$Cluster\"} + 0"
    },
    {
     "expr": "label_replace(max(dremio_api_cluster_up{job=~\"$Cluster\"}) by (cluster, job), \"_2_queue\", \"$1\", \"yarnqueue\", \"(.*)\")"
    }
   ]
  }
 ]
}