{
 "title": "Dremio Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(memory_heap_used, job)"
    }
   },
   {
    "name": "timeRange",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,2d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(memory_heap_used, job)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{job=~\"$Cluster\",group=\"Coordinator\"}) by (job) * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=~\"$Cluster\",group=\"Coordinator\"}) by (job)"
    }
   ]
  },
  {
   "title": "Executor Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dremio_sql_executors_Value{job=~\"$Cluster\",group=\"Coordinator\"})"
    }
   ]
  },
  {
   "title": "VDS Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dremio_sql_vds_count_Value{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_active_15m{job=~\"$Cluster\",group=\"Coordinator\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Active Jobs - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_active{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_15m{job=~\"$Cluster\",group=\"Coordinator\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Good Data Source Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dremio_api_source_status_Value{job=~\"$Cluster\",group=\"Coordinator\"} == 200)"
    }
   ]
  },
  {
   "title": "Bad Data Source Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dremio_api_source_status_Value{job=~\"$Cluster\",group=\"Coordinator\"} != 200)",
     "legendFormat": "count_bad"
    }
   ]
  },
  {
   "title": "Total Reflection Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reflections_active{job=~\"$Cluster\",group=\"Coordinator\"} + reflections_failed{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Usable Reflection Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reflections_active{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Failed Reflection Count - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reflections_failed{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Reflections Refreshing - Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reflections_refreshing{job=~\"$Cluster\",group=\"Coordinator\"}"
    }
   ]
  },
  {
   "title": "Canary query response",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(dremio_sql_canary_query_elapsedms_Value{job=\"$Cluster\", executor=\"dummy\"},\"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{ short_hostname }}"
    }
   ]
  },
  {
   "title": "Active Query Fragments",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "label_replace(fragments_active{job=\"$Cluster\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*)\") > 0",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "RPC Failures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "label_replace(rpc_failure_15m{job=\"$Cluster\", group=\"Executor\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*)\") > 0",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Queries waiting by Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Number of Queries" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(jobs_queue_UIPreviews_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_LowCostUserQueries_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_LowCostReflections_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_HighCostUserQueries_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_MetadataRefresh_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_UltraHighCostQueries_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    },
    {
     "expr": "label_replace(label_replace(jobs_queue_HighCostReflections_waiting{job=\"$Cluster\",group=\"Coordinator\"}, \"_0_cluster\", \"$1\", \"job\", \"(.*)\"),\"_1_queue\", \"$1\", \"__name__\", \"jobs_queue_(.*)_waiting\")",
     "legendFormat": "{{ _1_queue }}"
    }
   ]
  },
  {
   "title": "Disk Usage - Coordinators",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(max(node_filesystem_size_bytes{mountpoint=~\"/apps/dremio_prod_data\"}) by (instance, mountpoint), \"_0_short_hostname\", \"$1\", \"instance\", \"(.*):.*\")"
    },
    {
     "expr": "max(node_filesystem_avail_bytes {mountpoint=~\"/apps/dremio_prod_data\"}) by (instance, mountpoint)"
    },
    {
     "expr": "1-max((node_filesystem_free_bytes{mountpoint=~\"/apps/dremio_prod_data\"} / node_filesystem_size_bytes{mountpoint=~\"/apps/dremio_prod_data\"})) by (instance, mountpoint)"
    }
   ]
  },
  {
   "title": "CPU Usage - OS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) by (instance), \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Memory Usage - OS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-label_replace(avg(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes) by (instance), \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}"
    }
   ]
  },
  {
   "title": "Heap memory Usage - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(memory_heap_usage{job=\"$Cluster\",group=\"Coordinator\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{ short_hostname }}"
    }
   ]
  },
  {
   "title": "Direct  memory Usage - Executors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(dremio_sql_executor_direct_current_Value{job=\"$Cluster\",group=\"Coordinator\"}/dremio_sql_executor_direct_max_Value{job=\"$Cluster\"}) by (job, executor)",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Counts - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(gc_G1_Old_Generation_count{job=\"$Cluster\",group=\"Coordinator\"}[5m]), \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}:Major"
    },
    {
     "expr": "label_replace(rate(gc_G1_Young_Generation_count{job=\"$Cluster\",group=\"Coordinator\"}[5m]), \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}:Minor"
    }
   ]
  },
  {
   "title": "Garbage Collection Time - Coordinator",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(gc_G1_Old_Generation_time{job=\"$Cluster\",group=\"Coordinator\"} / gc_G1_Old_Generation_count{job=\"$Cluster\",group=\"Coordinator\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}:Major"
    },
    {
     "expr": "label_replace(gc_G1_Young_Generation_time{job=\"$Cluster\",group=\"Coordinator\"} / gc_G1_Young_Generation_count{job=\"$Cluster\",group=\"Coordinator\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "{{short_hostname}}:Minor"
    }
   ]
  }
 ]
}